name: ecom_store
description: An ecommerece platform to trade food products.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  package_info_plus: ^3.0.3
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  dartz: ^0.10.1
  get: ^4.6.5
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  connection_notifier: ^1.0.1
  another_flushbar: ^1.12.29
  cached_network_image: ^3.2.3
  fluttertoast: ^8.1.3
  tab_container: ^2.0.0
  dio: ^4.0.6
  otp_text_field: ^1.1.3
  uuid: ^3.0.7
  country_picker: ^2.0.19
  firebase_phone_auth_handler: ^1.0.8
  pinput: ^2.2.23
  path_provider: ^2.0.12
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  build_runner: ^2.3.3

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true


  assets:
   - assets/image/icons/
   - assets/image/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
