// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3_0nWhr1WZKp-mnNFE-EuiOdmEkaVaFs',
    appId: '1:754123965426:android:f590d340703c22e28a216b',
    messagingSenderId: '754123965426',
    projectId: 'e-com-store--169',
    storageBucket: 'e-com-store--169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEzGGhovWtJXG-BVvhgpKASIuWWyWwIik',
    appId: '1:754123965426:ios:1f97eb97341e8dca8a216b',
    messagingSenderId: '754123965426',
    projectId: 'e-com-store--169',
    storageBucket: 'e-com-store--169.appspot.com',
    androidClientId: '754123965426-fftetrm08slv64slh89l4ca5kh82jp1c.apps.googleusercontent.com',
    iosClientId: '754123965426-jbhdvq8b6s1khengcueddb67ugrarbks.apps.googleusercontent.com',
    iosBundleId: 'com.binarySequence.ecomStore',
  );
}
